on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  clojars:
    runs-on: ubuntu-latest

    steps:
      # This step checks out a copy of your repository.
      - uses: actions/checkout@v2

      - uses: jlesquembre/clojars-publish-action@0.3
        env:
          CLOJARS_USERNAME: kynthus
          CLOJARS_PASSWORD: CLOJARS_59a2c822611317a65cf36995f7d3088338b0205d035f581720b070d6c59d
